version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-app
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: apivendas-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
  pgadmin:
    image: dpage/pgadmin4
    container_name: apivendas-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
